gtex_to_alphagenome_terms = {
    "Adipose_Subcutaneous": ["adipose", "adipocyte", "preadipocyte", "fat", "lipocyte", "fibroblast", "stromal"],
    "Adipose_Visceral_Omentum": ["adipose", "adipocyte", "preadipocyte", "fat", "omentum", "lipocyte", "mesenchymal", "stromal"],
    "Adrenal_Gland": ["adrenal", "cortical", "adrenocortical", "chromaffin", "medulla", "steroidogenic"],
    "Artery_Aorta": ["artery", "aorta", "vascular", "endothelial", "smooth muscle", "myocyte", "vsmc", "pericyte"],
    "Artery_Tibial": ["artery", "vascular", "endothelial", "smooth muscle", "myocyte", "vsmc", "pericyte", "tibial"],
    "Brain_Amygdala": ["brain", "amygdala", "neur", "neuron", "neuronal", "astro", "astrocyte", "glia", "glial", "oligodend", "oligodendrocyte", "microglia", "neural stem"],
    "Brain_Anterior_cingulate_cortex_BA24": ["brain", "cingulate", "cortex", "cortical", "neur", "neuron", "neuronal", "astro", "astrocyte", "glia", "glial", "oligodend", "oligodendrocyte", "microglia", "neural stem"],
    "Brain_Caudate_basal_ganglia": ["brain", "caudate", "basal ganglia", "striatal", "neur", "neuron", "neuronal", "astro", "astrocyte", "glia", "glial", "oligodend", "oligodendrocyte", "microglia", "neural stem"],
    "Brain_Cerebellar_Hemisphere": ["brain", "cerebell", "cerebellar", "purkinje", "granule", "neur", "neuron", "neuronal", "astro", "astrocyte", "glia", "glial", "oligodend", "oligodendrocyte"],
    "Brain_Cerebellum": ["brain", "cerebell", "cerebellar", "purkinje", "granule", "neur", "neuron", "neuronal", "astro", "astrocyte", "glia", "glial", "oligodend", "oligodendrocyte"],
    "Brain_Cortex": ["brain", "cortex", "cortical", "neur", "neuron", "neuronal", "astro", "astrocyte", "glia", "glial", "oligodend", "oligodendrocyte", "microglia", "neural stem", "interneuron"],
    "Brain_Frontal_Cortex_BA9": ["brain", "frontal", "cortex", "cortical", "neur", "neuron", "neuronal", "astro", "astrocyte", "glia", "glial", "oligodend", "oligodendrocyte", "microglia", "neural stem", "interneuron"],
    "Brain_Hippocampus": ["brain", "hippocampus", "hippocampal", "neur", "neuron", "neuronal", "astro", "astrocyte", "glia", "glial", "oligodend", "oligodendrocyte", "microglia", "neural stem"],
    "Brain_Hypothalamus": ["brain", "hypothalam", "neur", "neuron", "neuronal", "astro", "astrocyte", "glia", "glial", "oligodend", "oligodendrocyte", "microglia", "neural stem"],
    "Brain_Nucleus_accumbens_basal_ganglia": ["brain", "nucleus accumbens", "basal ganglia", "striatal", "neur", "neuron", "neuronal", "astro", "astrocyte", "glia", "glial", "oligodend", "oligodendrocyte", "microglia"],
    "Brain_Spinal_cord_cervical_c-1": ["spinal", "cord", "motor neuron", "neur", "neuron", "neuronal", "astro", "astrocyte", "glia", "glial", "oligodend", "oligodendrocyte", "microglia", "neural stem"],
    "Brain_Substantia_nigra": ["brain", "substantia nigra", "dopamin", "neur", "neuron", "neuronal", "astro", "astrocyte", "glia", "glial", "oligodend", "oligodendrocyte", "microglia"],
    "Breast_Mammary_Tissue": ["breast", "mammary", "luminal", "basal", "myoepithelial", "fibroblast", "ductal"],
    "Cells_Cultured_fibroblasts": ["fibroblast", "stromal", "mesenchymal", "cultured fibroblast"],
    "Cells_EBV-transformed_lymphocytes": ["lymphocyte", "b-cell", "b-cell", "ebv", "immune", "blood"],
    "Colon_Sigmoid": ["colon", "colonic", "sigmoid", "intestinal", "enterocyte", "colonocyte", "goblet", "crypt"],
    "Colon_Transverse": ["colon", "colonic", "transverse", "intestinal", "enterocyte", "colonocyte", "goblet", "crypt"],
    "Esophagus_Gastroesophageal_Junction": ["esophagus", "esophageal", "gastroesophageal", "junction", "squamous", "keratinocyte"],
    "Esophagus_Mucosa": ["esophagus", "esophageal", "mucosa", "squamous", "keratinocyte", "basal keratinocyte"],
    "Esophagus_Muscularis": ["esophagus", "esophageal", "muscularis", "smooth muscle", "myocyte", "muscle"],
    "Heart_Atrial_Appendage": ["heart", "cardiac", "cardiomyocyte", "atrial", "myocyte", "fibroblast", "endothelial", "pericyte"],
    "Heart_Left_Ventricle": ["heart", "cardiac", "cardiomyocyte", "ventric", "myocyte", "fibroblast", "endothelial", "pericyte"],
    "Kidney_Cortex": ["kidney", "renal", "nephron", "tubule", "tubular", "podocyte", "glomerular", "proximal tubule", "distal tubule"],
    "Liver": ["liver", "hepatic", "hepatocyte", "kupffer", "stellate", "cholangiocyte", "sinusoidal", "hepatoblast"],
    "Lung": ["lung", "pulmonary", "alveolar", "airway", "pneumocyte", "type i pneumocyte", "type ii pneumocyte", "bronchial", "fibroblast"],
    "Minor_Salivary_Gland": ["salivary", "gland", "acinar", "ductal", "myoepithelial"],
    "Muscle_Skeletal": ["muscle", "myocyte", "myoblast", "myotube", "myofiber", "skeletal muscle", "sarcomere"],
    "Nerve_Tibial": ["nerve", "schwann", "glia", "glial", "peripheral nerve", "axon", "neur", "neuron"],
    "Ovary": ["ovary", "ovarian", "granulosa", "theca", "oocyte", "follicular", "stromal"],
    "Pancreas": ["pancreas", "pancreatic", "acinar", "ductal", "islet", "beta-cell", "alpha-cell", "delta-cell"],
    "Pituitary": ["pituitary", "pituitary gland", "hormone", "adenohypophy", "neuroendocrine", "pituitary cell"],
    "Prostate": ["prostate", "prostatic", "basal", "luminal", "stromal", "secretory"],
    "Skin_Not_Sun_Exposed_Suprapubic": ["skin", "keratinocyte", "epiderm", "epidermal", "dermal", "fibroblast", "melanocyte", "sebocyte"],
    "Skin_Sun_Exposed_Lower_leg": ["skin", "keratinocyte", "epiderm", "epidermal", "dermal", "fibroblast", "melanocyte", "sebocyte"],
    "Small_Intestine_Terminal_Ileum": ["intestine", "ileum", "intestinal", "enterocyte", "goblet", "crypt", "mucosa", "paneth"],
    "Spleen": ["spleen", "splenic", "immune", "lymphocyte", "b-cell", "t-cell", "monocyte", "macrophage", "dendritic", "plasma"],
    "Stomach": ["stomach", "gastric", "chief", "parietal", "mucous", "foveolar", "gland"],
    "Testis": ["testis", "testicular", "spermat", "spermatogon", "spermatocyte", "sertoli", "leydig"],
    "Thyroid": ["thyroid", "thyrocyte", "follicular", "parafollicular"],
    "Uterus": ["uterus", "uterine", "endometrial", "stromal", "myometrial", "decidual"],
    "Vagina": ["vagina", "vaginal", "squamous", "keratinocyte", "stromal"],
    "Whole_Blood": ["blood", "immune", "lymph", "lymphocyte", "monocyte", "leukocyte", "hematopo", "t-cell", "b-cell", "nk-cell", "granulocyte", "neutrophil", "eosinophil", "basophil", "macrophage", "dendritic"],
}
